repos:
  - repo: local
    hooks:
      - id: markdownlint
        name: markdownlint
        entry: markdownlint -c .markdownlint.yml
        language: system
        files: \.md$
        types: [markdown]


